languaje: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '16'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - edidier615@gmail.com
      - 20183ti035@utez.edu.mx
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master